project:
  title: "Patoloji ve Bilişim"

editor: visual

execute:
  freeze: false  # whether to re-execute computational content during project render

format:
  gfm:
    preview-mode: raw
  pdf: default
  epub: default
  html: default
